export const OK=0, ERR_NOT_OWNER=-1, ERR_NO_PATH=-2, ERR_NAME_EXISTS=-3, ERR_BUSY=-4, ERR_NOT_FOUND=-5,
  ERR_NOT_ENOUGH_ENERGY=-6, ERR_NOT_ENOUGH_RESOURCES=-6, ERR_INVALID_TARGET=-7, ERR_FULL=-8, ERR_NOT_IN_RANGE=-9,
  ERR_INVALID_ARGS=-10, ERR_TIRED=-11, ERR_NO_BODYPART=-12, ERR_NOT_ENOUGH_EXTENSIONS=-6;
export const MOVE='move', WORK='work', CARRY='carry', ATTACK='attack', RANGED_ATTACK='ranged_attack', HEAL='heal', TOUGH='tough';
export const TOP=1, TOP_RIGHT=2, RIGHT=3, BOTTOM_RIGHT=4, BOTTOM=5, BOTTOM_LEFT=6, LEFT=7, TOP_LEFT=8;
export const TERRAIN_PLAIN=0, TERRAIN_WALL=1, TERRAIN_SWAMP=2;
export const BODYPART_HITS=100, RANGED_ATTACK_POWER=10, RANGED_ATTACK_DISTANCE_RATE={0:1,1:1,2:0.4,3:0.1}, ATTACK_POWER=30,
  HEAL_POWER=12, RANGED_HEAL_POWER=4, CARRY_CAPACITY=50, REPAIR_POWER=100, DISMANTLE_POWER=50, REPAIR_COST=0.01,
  DISMANTLE_COST=0.005, HARVEST_POWER=2, BUILD_POWER=5;
export const OBSTACLE_OBJECT_TYPES=['creep','tower','constructedWall','spawn','extension','link'];
// башня АРЕНЫ (документация arena.screeps.com, 09.2026): 1000 в упор, −50 за клетку, кулдаун 10, ёмкость — один выстрел
export const TOWER_ENERGY_COST=10, TOWER_RANGE=20, TOWER_HITS=3000, TOWER_CAPACITY=10, TOWER_POWER_ATTACK=1000, TOWER_POWER_HEAL=600,
  TOWER_POWER_REPAIR=200, TOWER_OPTIMAL_RANGE=1, TOWER_FALLOFF_RANGE=21, TOWER_FALLOFF=1, TOWER_COOLDOWN=10;
export const BODYPART_COST={move:50,work:100,attack:80,carry:50,heal:250,ranged_attack:150,tough:10};
export const MAX_CREEP_SIZE=50, CREEP_SPAWN_TIME=3, RESOURCE_ENERGY='energy', RESOURCES_ALL=['energy'], SOURCE_ENERGY_REGEN=10,
  RESOURCE_DECAY=1000, MAX_CONSTRUCTION_SITES=10, CONSTRUCTION_COST={StructureTower:1250,StructureExtension:200,StructureRoad:10,StructureContainer:100,StructureWall:100,StructureRampart:200,StructureSpawn:1000}, STRUCTURE_PROTOTYPES={},
  CONSTRUCTION_COST_ROAD_SWAMP_RATIO=5, CONSTRUCTION_COST_ROAD_WALL_RATIO=150, CONTAINER_HITS=300, CONTAINER_CAPACITY=2000,
  WALL_HITS=10000, WALL_HITS_MAX=10000, RAMPART_HITS=10000, RAMPART_HITS_MAX=10000, ROAD_HITS=500, ROAD_WEAROUT=1,
  EXTENSION_HITS=100, EXTENSION_ENERGY_CAPACITY=100, SPAWN_ENERGY_CAPACITY=1000, SPAWN_HITS=3000;
export const EFF_CONSTRUCTION_BOOST='eff_construction_boost', EFF_HEAL_BOOST='eff_heal_boost', EFF_RANGED_ATTACK_BOOST='eff_ranged_attack_boost',
  EFF_ATTACK_BOOST='eff_attack_boost', EFF_WORK_BOOST='eff_work_boost', EFF_MOVE_BOOST='eff_move_boost',
  EFF_ATTACK_MODIFIER='eff_attack_modifier', EFF_RANGED_ATTACK_MODIFIER='eff_ranged_attack_modifier', EFF_HEAL_MODIFIER='eff_heal_modifier',
  EFF_DAMAGE_TAKEN_MODIFIER='eff_damage_taken_modifier', EFF_FATIGUE_MODIFIER='eff_fatigue_modifier', EFF_HITS_LOSS='eff_hits_loss';
